CREATE DATABASE JediLibraryDB;

use JediLibraryDB;

CREATE TABLE Permissions (
PermID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(32) NOT NULL
);

CREATE TABLE Users (
UserID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(64) NOT NULL,
HashedPassword VARCHAR(64) NOT NULL,
ClassID INT UNSIGNED NOT NULL,
FOREIGN KEY (ClassID) REFERENCES Permissions(PermID)
);

CREATE TABLE Knights (
KnightID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(32) NOT NULL,
ClassOdJediOrder VARCHAR(32) NOT NULL
);

CREATE TABLE Holocrons (
HoloID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Title VARCHAR(64) NOT NULL,
YearOfPublish VARCHAR(32) NOT NULL,
Contains VARCHAR(1924),
AuthorID INT UNSIGNED NOT NULL,
ClassID INT UNSIGNED NOT NULL,
FOREIGN KEY(AuthorID) REFERENCES Knights(KnightID),
FOREIGN KEY(ClassID) REFERENCES Permissions(PermID)
);

CREATE TABLE Missions (
MissionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
YearOfDone VARCHAR(32),
Title VARCHAR(64) NOT NULL,
ClassID INT UNSIGNED NOT NULL,
MembershipID INT UNSIGNED NOT NULL,
PlaceOfMissionID INT UNSIGNED NOT NULL,
FOREIGN KEY(ClassID) REFERENCES Permissions(PermID)
FOREIGN KEY(MembershipID) REFERENCES MissionMembership(????)
FOREIGN KEY(PlaceOfMissionID) REFERENCES PlaceOfMission(????)
);

CREATE TABLE MissionMembership (
MissionID INT UNSIGNED,
KnightID INT UNSIGNED,
FOREIGN KEY (MissionID) REFERENCES Missions(MissionID),
FOREIGN KEY (KnightID) REFERENCES Knights(KnightID),
PRIMARY KEY(MissionID, KnightID)
);

CREATE TABLE Planets (
PlanetID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(32) NOT NULL,
Sector VARCHAR(32)
);

CREATE TABLE PlaceOfMission (
PlanetID INT UNSIGNED,
MissionID INT UNSIGNED,
FOREIGN KEY(PlanetID) REFERENCES Planets(PlanetID),
FOREIGN KEY(MissionID) REFERENCES Missions(MissionID),
PRIMARY KEY(PlanetID, MissionID)
);

