insert into Planets
Values
('Abafar','Sprizen sector'), 
('Aeneid','Kessel sector'), 
('Alderaan','Alderaan sector'), 
('Aleen','Bright Jewel sector'), 
('Aleen Minor','Bright Jewel sector'), 
('Allyuen','Anoat sector'), 
('Anantapar','Anoat sector'), 
('Anoat','Anoat sector'), 
('Arkanis','Arkanis sector'), 
('Artiod Minor','Morellian Commonwealth'), 
('Asmeru','Senex sector'), 
('Atollon','Lothal sector'), 
('Bardotta','Shasos sector'), 
('Basteel','Corva sector'), 
('Batonn','Batonn sector'), 
('Bavva','Anoat sector'), 
('Belderone','Tion Cluster'), 
('Bendeluum','Anoat sector'), 
('Bespin','Anoat sector'), 
('Bonadan','Corporate Sector'), 
('Botajef','Belsmuth sector'), 
('Burnin Konn','Anoat sector'), 
('Cantonica','Corporate Sector'), 
('Cato Neimoidia','Quellor sector'), 
('Christophsis','Savareen sector'), 
('Concord Dawn','Mandalore sector'), 
('Corellia','Corellian sector'), 
('Coruscant','Corusca sector, Coruscant subsector'), 
('Cosia','Cosian Space'), 
('Cos Secundu','Cosian Space'), 
('Council','Anoat sector'), 
('Crucival','Tion Hegemony'), 
('Cyrkon','Hutt Space'), 
('Dagobah','Sluis sector'), 
('Dandoran','Hutt Space'), 
('Dantooine','Raioballo sector'), 
('Darlyn Boda','Anoat sector'), 
('Dathomir','Quelli sector'), 
('Delphon','Anoat sector'), 
('Denash','Batonn sector'), 
('Duro','Duro sector'), 
('Eadu','Bheriz sector'), 
('Endor','Moddell sector'), 
('Epiphany','Corporate Sector'), 
('Eriadu','Seswenna sector'), 
('Ertegas','Anoat sector'), 
('Fest','Atrivis sector'), 
('Florrum','Sertar sector'), 
('Galaan','Corva sector'), 
('Gamorr','Galov sector'), 
('Garel','Lothal sector'), 
('Gentes','Anoat sector'), 
('Geonosis','Arkanis sector'), 
('Gerrenthum','Anoat sector'), 
('Gigor','Tynquay sector'), 
('Grange','Rocantor sector'), 
('Gutretee','Anoat sector'), 
('Hosra','Anoat sector'), 
('Hoth','Anoat sector'), 
('Iktotchon','Narvath sector'), 
('Ilum','7G sector'), 
('Injopan','Kessel sector'), 
('Ione','Anoat sector'), 
('Ison','Anoat sector'), 
('Jaresh','Corva sector'), 
('Jhas','Anoat sector'), 
('Kalevala','Mandalore sector'), 
('Kamino','Abrion sector'), 
('Karfeddion','Senex sector'), 
('Karlinus','Chommell sector'), 
('Kashyyyk','Mytaranor sector'), 
('Kessel','Kessel sector'), 
('Kintan','Hutt Space'), 
('Kirtarkin','Anoat sector'), 
('Klatooine','Hutt Space'), 
('Krownest','Mandalore sector'), 
('Lah'mu','Raioballo sector'), 
('Lefrani','Atravis sector'), 
('Lola Sayu','Belderone sector'), 
('Lothal','Lothal sector'), 
('Lutrillia','Greater Javin'), 
('Malastare','Dustig sector'), 
('Mandalore','Mandalore sector'), 
('Mandrine','Kessel sector'), 
('Maridun','Rolion sector'), 
('Mataou','Anoat sector'), 
('Mexeluine','Anoat sector'), 
('Mijos','Anoat sector'), 
('Mimban','Circarpous sector'), 
('Mirrin Prime','Mirrin sector'), 
('Miser','Anoat sector'), 
('Mon Cala','Calamari sector'), 
('Moonus Mandel','Bothan Space'), 
('Morellia','Morellian Commonwealth'), 
('Mustafar','Atravis sector'), 
('Mydasos','Dalicron sector'), 
('Mykapo','Mykapo sector'), 
('Naboo','Chommell sector'), 
('NaJedha','Terrabe sector, Freestanding subsectors'), 
('Nal Hutta','Hutt Space'), 
('Neral','Corellian sector'), 
('Nothoiin','Anoat sector'), 
('N'Zoth','Koornacht Cluster'), 
('Oba Diah','Kessel sector'), 
('Onderon','Japrael sector'), 
('Oon','Lothal sector'), 
('Ord Mantell','Bright Jewel sector'), 
('Orn Kios','Anoat sector'), 
('Orto Plutonia','Sujimis sector'), 
('Phindar','Mandalore sector'), 
('Polis Massa','Subterrel sector'), 
('Polmanar','Anoat sector'), 
('Pujool','Anoat sector'), 
('Randa','Kessel sector'), 
('Raxus','Tion Hegemony'), 
('Raxus Prime','Tion Hegemony'), 
('Rishi','Abrion sector'), 
('Rodia','Savareen sector'), 
('Ryloth','Gaulus sector'), 
('Saki','Hutt Space'), 
('Saleucami','Suolriep sector'), 
('Salient I','Corporate Sector'), 
('Salient II','Corporate Sector'), 
('Sammun','Batonn sector'), 
('Scarif','Abrion sector'), 
('Scipio','Albarrio sector'), 
('Seelos','Kwymar sector'), 
('Sembla','Mahrusha sector'), 
('Sesid','Corva sector'), 
('Seswenna','Seswenna sector'), 
('Sriluur','Hutt Space'), 
('Starkiller Base','7G sector'), 
('Stygeon Prime','Nuiri sector'), 
('Sullust','Sullust sector'), 
('Takodana','Tashtor sector'), 
('Tatooine','Arkanis sector'), 
('Telerath','Nouane sector'), 
('Teth','Baxel sector'), 
('Tibrin','Hadar sector'), 
('Tilurus','Kessel sector'), 
('Tokmia','Anoat sector'), 
('Toydaria','Hutt Space'), 
('Trandosha','Mytaranor sector'), 
('Trionak','Kiax Nebula, Anoat sector'), 
('Tund','Centrality'), 
('Uba','Barsa sector'), 
('Ukio','Abrion sector'), 
('Umbara','Ghost Nebula'), 
('Utapau','Tarabba sector'), 
('Vandor','Sloo sector'), 
('Vetine','Merrick sector'), 
('Vodran','Si'Klaata Cluster'), 
('Wobani','Bryx sector'), 
('Yavin','Gordian Reach'), 
('Zerm','Kessel sector'), 
('Zhanox','Anoat sector');