use JediLibraryDB

insert into Missions
values
('22 BBY','Antar 4 schism','1'),
('22 BBY','Border dispute on Ansion','1'),
('22 BBY','Plot to assassinate Padme Amidala','1'),
('22 BBY','Mission to Kamino','1'),
('22 BBY','Dogfight over Geonosis','1'),
('22 BBY','Mission to rescue Shmi Skywalker Lars ','1'),
('22 BBY','Battle of Geonosis','1'),
('22 BBY','Attack on a Republic troop transport','1'),
('22 BBY','Battle of Arantara','3'),
('22 BBY','Battle of Murkhana','3'),
('22 BBY','Battle of Christophsis','3'),
('22 BBY','Battle of Teth','3'),
('22 BBY','Mission to Jabba''s Palace','3'),
('22 BBY','Raid on Ziro the Hutt''s Coruscant pleasure palace ','3'),
('22 BBY','Battle of Aargonar','3'),
('22 BBY','Battle of Ryloth','3'),
('22 BBY','Mission to Rugosa','3'),
('22 BBY','Battle of Abregado','3'),
('22 BBY','Battle of the Ryndellia system','3'),
('22 BBY','Battle of the Kaliida Nebula','3'),
('22 BBY','Battle near the Kaliida Nebula ','3'),
('22 BBY','Battle of Mimban','3'),
('22 BBY','Battle of Tibrin','3'),
('22 BBY','Battle of the Rishi moon','3'),
('22 BBY','Battle of Falleen','3'),
('22 BBY','Battle of Bothawui','3'),
('22 BBY','Ambush on the Vulture''s Claw','3'),
('22 BBY','Mission to sweep outer corridor of space','3'),
('22 BBY','Mission to Skytop Station ','3'),
('22 BBY','Mission to Rodia','3'),
('22 BBY','Rescue on the Tranquility','3'),
('22 BBY','Mission to Vassek 3 ','3'),
('22 BBY','Skirmish at Vanqor','3'),
('22 BBY','Mission to Florrum ','3'),
('22 BBY','Battle of Quell','3'),
('22 BBY','Defense of Maridun ','3'),
('22 BBY','Skirmish on Orto Plutonia','3'),
('22 BBY','Battle of Orto Plutonia ','3'),
('21 BBY','Siege of Grange','3'),
('21 BBY','Mission to Merj','3'),
('21 BBY','Rescue of Galen Erso ','3'),
('21 BBY','Raid on Nuvo Vindi''s laboratory','3'),
('21 BBY','Mission to Iego','3'),
('21 BBY','First battle of Felucia','3'),
('21 BBY','Mission to the Jedi Temple','3'),
('21 BBY','Battle of Devaron','3'),
('21 BBY','Mission to Glee Anselm','3'),
('21 BBY','Mission to Naboo','3'),
('21 BBY','Second Mission to Rodia','3'),
('21 BBY','Mission to Mustafar','1'),
('21 BBY','Mission to Black Stall Station ','1'),
('21 BBY','Destruction of the Felucia medical station','1'),
('21 BBY','Skirmish on Felucia ','1'),
('21 BBY','Battle of Malastare','1'),
('21 BBY','Zillo Beast incident ','1'),
('21 BBY','Mission to Cato Neimoidia','1'),
('21 BBY','Battle near Dorin','3'),
('21 BBY','Second Battle of Geonosis','3'),
('21 BBY','Battle of Dantooine','3'),
('21 BBY','Skirmish aboard TB-73 ','3'),
('21 BBY','Capture of Eeth Koth','3'),
('21 BBY','Battle of Saleucami ','3'),
('21 BBY','Attack on a Republic cruiser','3'),
('21 BBY','Bombing of the memorial shrine','3'),
('21 BBY','Skirmish on Concordia','3'),
('21 BBY','Skirmish aboard the Coronet','3'),
('21 BBY','Plot to assassinate Satine Kryze','3'),
('21 BBY','Bombing on Kalevala ','3'),
('21 BBY','Sabotage of the Endurance','3'),
('21 BBY','Mission to Vanqor ','3'),
('21 BBY','Second mission to Florrum','3'),
('21 BBY','Skirmish at the Sundari docks','3'),
('21 BBY','Mandalorian black market conspiracy','3'),
('21 BBY','Balith civil war','3'),
('21 BBY','Alderaan Refugee Conference','3'),
('21 BBY','Battle of Kamino','3'),
('21 BBY','Blockade of Pantora','3'),
('21 BBY','Kidnapping of the Papanoida daughters','3'),
('21 BBY','Rescue on the Pantora Droid Control Ship','3'),
('21 BBY','Rescue in Chalmun''s Cantina ','3'),
('21 BBY','Senate hostage crisis','3'),
('21 BBY','Showdown on Teth ','3'),
('21 BBY','Bombing of Coruscant''s central power distribution grid','3'),
('21 BBY','Attack on Confederate people ','3'),
('20 BBY','Battle of Sullust','3'),
('20 BBY','Mission to Serenno','3'),
('20 BBY','Devaron massacre','3'),
('20 BBY','Showdown at Toydaria ','3'),
('20 BBY','Mission to Mortis','3'),
('20 BBY','Capture of Even Piell','3'),
('20 BBY','Battle of Lola Sayu ','3'),
('20 BBY','Second Battle of Felucia','3'),
('20 BBY','Skirmish on Wasskah ','3'),
('20 BBY','Battle of Mon Cala','3'),
('20 BBY','Skirmish on Naboo','3'),
('20 BBY','Battle of Patitite Pattuna','3'),
('20 BBY','Rescue of Adi Gallia ','3'),
('20 BBY','Battle of Umbara','3'),
('20 BBY','Battle of Kiros','3'),
('20 BBY','Battle of Zygerria','3'),
('20 BBY','Battle of Kadavo ','3'),
('20 BBY','Battle on Carlac','3'),
('20 BBY','Riot at the Republic Judiciary Central Detention Center','3'),
('20 BBY','Showdown on Orondia','3'),
('20 BBY','Skirmish in Theed ','3'),
('20 BBY','Battle of Dathomir','3'),
('20 BBY','Safe cargo objective','3'),
('20 BBY','Mission to Lotho Minor','3'),
('20 BBY','Massacre on Raydonia','3'),
('20 BBY','Skirmish above Raydonia ','3'),
('20 BBY','Onderonian Civil War','3'),
('20 BBY','Raid on the Crucible','3'),
('20 BBY','Attack on Obi-Wan Kenobi''s fleet','3'),
('20 BBY','Rescue on Florrum','4'),
('20 BBY','Battle on Florrum ','4'),
('20 BBY','Battle over unidentified planet','4'),
('20 BBY','Mission to Aut-O''s flagship','4'),
('20 BBY','Escape from Abafar','4'),
('20 BBY','Carida incident ','4'),
('20 BBY','Duel at unidentified Outer Rim spaceport','4'),
('20 BBY','Raid on the Cybloc transfer station','4'),
('20 BBY','Skirmish on Florrum','4'),
('20 BBY','Mission to Mustafar','4'),
('20 BBY','Mission to Nal Hutta','4'),
('20 BBY','Attack on Jabba''s Palace','4'),
('20 BBY','Takeover of Mandalore','4'),
('20 BBY','Mandalorian civil war ','4'),
('19 BBY','Defense of Cato Neimoidia','4'),
('19 BBY','Bombing of the Jedi Temple hangar','4'),
('19 BBY','Escape from the Republic military base','4'),
('19 BBY','Duel at the Jedi Temple ','4'),
('19 BBY','Battle of Ringo Vinda','4'),
('19 BBY','Mission to Level 1325','4'),
('19 BBY','Mission to Scipio','4'),
('19 BBY','Invasion of Scipio','4'),
('19 BBY','Mission to Bardotta','4'),
('19 BBY','Mission to Zardossa Stix','4'),
('19 BBY','Mission to Oba Diah','4'),
('19 BBY','Mission to Moraband','4'),
('19 BBY','Mission to Utapau','4'),
('19 BBY','Insurrection on Yalvik Prime','4'),
('19 BBY','Battle for Anaxes','4'),
('19 BBY','Mission to Skako Minor','4'),
('19 BBY','Attack on Mahranee','4'),
('19 BBY','Capture of Moregi','4'),
('19 BBY','Rescue of Marg Krim''s family','4'),
('19 BBY','Mission to Raxus ','3'),
('19 BBY','Escape from the Spire','3'),
('19 BBY','Battle of Zanbar','3'),
('19 BBY','Battle on Ord Mantell','3'),
('19 BBY','Assault on Vizsla Keep 09','3'),
('19 BBY','Second battle of Dathomir ','3'),
('19 BBY','Mission to Serenno','3'),
('19 BBY','Rescue of Quinlan Vos','3'),
('19 BBY','Destruction of the Separatist supply storage base','3'),
('19 BBY','Destruction of the Vanqor listening post','3'),
('19 BBY','Second battle of Christophsis ','3'),
('19 BBY','Battle of Haruun Kal','3'),
('19 BBY','Bombing at the Jedi Temple','3'),
('19 BBY','Skirmish on Kardoa','3'),
('19 BBY','Third Battle of Mygeeto','3'),
('19 BBY','Battle on Lokori','4'),
('19 BBY','Escape from Geonosis','4'),
('19 BBY','Battle of Coruscant','4'),
('19 BBY','Siege of Mandalore','1'),
('19 BBY','Outer Rim Sieges','4'),
('19 BBY','Battle of Utapau','1'),
('19 BBY','Capture of Cato Neimoidia','4'),
('19 BBY','Battle of Kashyyyk','1'),
('19 BBY','Assault on Mygeeto','3'),
('19 BBY','Siege of Saleucami','3'),
('19 BBY','Battle of Felucia','3'),
('19 BBY','Conquest of Kaller ','3'),
('19 BBY','Duel in Palpatine''s office','3'),
('19 BBY','Order 66','4'),
('19 BBY','Attack on the Jedi Temple ','3'),
('19 BBY','Mission to Mustafar ','3'),
('19 BBY','Duel on Mustafar','3'),
('19 BBY','Duel in the Galactic Senate','3'),
('19 BBY','Recapture of Darth Vader''s starship','3'),
('19 BBY','Attack on Brighthome','3'),
('19 BBY','Mission to the river moon of Al''doleem','3'),
('19 BBY','Hunt for Jocasta Nu','3'),
('19 BBY','Assassination attempts on Darth Vader','3'),
('19 BBY','Ambush in the Coruscant system','3'),
('18 BBY','Theft of the IG-RM droids','3'),
('18 BBY','Rescue of Caleb Dume','3'),
('18 BBY','Antar Atrocity','3'),
('18 BBY','Western Reaches pacification operations','3'),
('18 BBY','Hunt on Chandar''s Folly','3'),
('18 BBY','Hunt for Eeth Koth','3'),
('18 BBY','Rogue Inquisitor chase','3'),
('13 BBY','Capture of Galen Erso','3'),
('12 BBY','Battle of Fortress Vader','3'),
('11 BBY','Annexation of Jelucan','3'),
('10 BBY','Mimban campaign','3'),
('10 BBY','Heist on Vandor','3'),
('10 BBY','Raid on Kessel','3'),
('10 BBY','Skirmish on Savareen ','3'),
('18 BBY','Rebellion on Umbara','3'),
('18 BBY','Campaigns of Saw Gerrera''s Partisans','4'),
('18 BBY','Campaign at Salient ','1'),
('18 BBY','Occupation of Mon Cala','4'),
('18 BBY','Battle of Dac City','4'),
('18 BBY','Attack on Bergon''s sky-base','4'),
('18 BBY','Skirmish in Bel City','1'),
('18 BBY','Duel in the Royal Command Bunker ','4'),
('18 BBY','Uprising on Raada','1'),
('18 BBY','Heist at the Twin Horns Storage','4'),
('18 BBY','Ryloth summer riots','4'),
('14 BBY','Mission to hijack an Imperial weapons shipment','1'),
('14 BBY','Mission to Ryloth','4'),
('14 BBY','Relief mission to Ryloth','3'),
('14 BBY','Berch Teller campaign','3'),
('14 BBY','Attack on Sentinel Base','3'),
('14 BBY','Mission to Murkhana','2'),
('14 BBY','Attack on Galidraan Station','2'),
('14 BBY','Attack on Lucazec','2'),
('14 BBY','Battle in the Phindar system','2'),
('14 BBY','Attack on the Nouane system','2'),
('14 BBY','Battle near the Gulf of Tatooine ','2'),
('11 BBY','Gorse conflict','2'),
('10 BBY','Mimban Campaign','2'),
('7 BBY','Mission to Horuz','2'),
('6 BBY','Mission to Inusagi','2'),
('6 BBY','Malkhani Insurrections','2'),
('6 BBY','Westhills bombing attempt','2'),
('6 BBY','Westhills massacre','2'),
('6 BBY','Westhills skirmish','2'),
('5 BBY','Transportation Ministry data breach','2'),
('5 BBY','Raid on an Imperial supply convoy','2'),
('5 BBY','Attack on a Lothal airfield','2'),
('5 BBY','Heist in Capital City','2'),
('5 BBY','Mission to free Wookiee prisoners','2'),
('5 BBY','Mission to steal Imperial weapons','2'),
('5 BBY','Attack on Imperial Troop Transports','2'),
('5 BBY','Duel on Stygeon Prime','2'),
('5 BBY','Mission to destroy a kyber crystal','2'),
('5 BBY','Attack on an Imperial convoy','2'),
('5 BBY','Skirmish on Vyndal','2'),
('4 BBY','Bombing at the Empire Day parade','2'),
('4 BBY','Rescue of Tseebo','2'),
('4 BBY','Mission to Lando Calrissian''s farm','2'),
('4 BBY','Assault on the Gray Syndicate','2'),
('4 BBY','Trap in the Old Republic Senate Building','2'),
('4 BBY','Raid near Jalath','2'),
('4 BBY','Raid on the communications tower','2'),
('4 BBY','Action at Mustafar','2'),
('4 BBY','Rescue of Dhara Leonis','2'),
('4 BBY','Mission to rescue Janard','2'),
('4 BBY','Mission to steal Imperial shield generators','2'),
('4 BBY','Siege of Lothal','2'),
('4 BBY','Mission to Lothal','2'),
('4 BBY','Attack on Phoenix Squadron ','2'),
('4 BBY','Assault on Seelos','2'),
('4 BBY','Mission to Absanz','2'),
('4 BBY','Skirmish aboard a Republic medical station','2'),
('4 BBY','Skirmish in Nixus Hub 2','2'),
('4 BBY','Blockade of Ibaar','2'),
('4 BBY','Skirmish on Thrad','2'),
('4 BBY','Skirmish in the Garel City Spaceport','2'),
('4 BBY','Rescue on the Imperial Interdictor','2'),
('4 BBY','Battle with Phoenix Squadron','2'),
('4 BBY','Duel in Hammertown','2'),
('4 BBY','Skirmish on Imvur','2'),
('4 BBY','Duel on Bilzen','2'),
('4 BBY','Revolt in an Imperial prison','2'),
('4 BBY','Battle on Garel','2'),
('3 BBY','Attack on Calderos','2'),
('3 BBY','Assassination of Quarsh Panaka','2'),
('3 BBY','Arrests on Christophsis','2'),
('3 BBY','Evacuation of Paucris Major','2'),
('3 BBY',' Auction on Cantonica','2'),
('3 BBY',' Skirmish on Freerago''s Satellite Diner and Motel','2'),
('3 BBY','Mission to Garel','2'),
('3 BBY','Mission on Lothal','2'),
('3 BBY','Dogfight over Concord Dawn','2'),
('3 BBY','Mission to the third moon of Concord Dawn','2'),
('3 BBY','Rediscovery of Lira San','2'),
('3 BBY','Heist at the Asteroid Belt Gas Refinery','2'),
('3 BBY','Mission to Ryloth','2'),
('3 BBY','Ambush on an Imperial construction module','2'),
('3 BBY','Duel on Oosalon','2'),
('3 BBY','Rescue of Ezra Bridger','2'),
('3 BBY','Attack on Phoenix Squadron','2'),
('3 BBY','Mission to Thune City','2'),
('3 BBY','Mission to Malachor','2'),
('2 BBY','Batonn sector insurgency','2'),
('2 BBY','Battle of Denash','2'),
('2 BBY','Battle of Sammun','2'),
('2 BBY','Batonn insurgency','2'),
('2 BBY','Battle of Scrim Island','2'),
('2 BBY','Siege of the Creekpath Mining and Refining complex ','2'),
('2 BBY','Rescue of Hondo Ohnaka','2'),
('2 BBY','Mission to Reklam Station','2'),
('2 BBY','Maul''s capture of the Ghost crew','2'),
('2 BBY','Massacre near Teralov','2'),
('2 BBY','Escape from Skystrike Academy','2'),
('2 BBY','Second mission to Ryloth','2'),
('2 BBY','Mission to Agamar','2'),
('2 BBY','Second mission to the third moon of Concord Dawn','2'),
('2 BBY','Skirmish over Mykapo','2'),
('2 BBY','Blockade over Synistahg','2'),
('2 BBY','Mission to loot an Imperial cargo ship','2'),
('2 BBY','Infiltration of the Imperial Armory Complex','2'),
('2 BBY','Skirmish on Dathomir','2'),
('2 BBY','Rescue of Ketsu Onyo','2'),
('2 BBY','Mission to investigate Geonosis','2'),
('2 BBY','EXD-9''s infiltration of Chopper Base','2'),
('2 BBY','Mandalorian civil war','2'),
('2 BBY','Skirmish on Krownest ','2'),
('2 BBY','Rescue of Alexsandr Kallus','2'),
('2 BBY','Ghorman Massacre','2'),
('2 BBY','Operation Handoff','2'),
('2 BBY','Mission to recover Imperial codes','2'),
('2 BBY','Mission to Tatooine','2'),
('2 BBY','Battle of Atollon','2'),
('2 BBY','Skirmish on Batuu','2'),
('2 BBY','Battle of Mokivj','2'),
('1 BBY','Battle against Grysk forces','2'),
('1 BBY','Mandalorian civil war','2'),
('1 BBY','Mission to Mandalore ','2'),
('1 BBY','Mission to Jalindi','2'),
('1 BBY','Mission to Faos Station','2'),
('1 BBY','Theft of the TIE Defender Elite','2'),
('1 BBY','Hijacking of Crawler 413-24','2'),
('1 BBY','Attack on Lothal','2'),
('1 BBY','Rescue of Hera Syndulla','2'),
('1 BBY','Mission to the Lothal Jedi Temple','2'),
('1 BBY','Liberation of Lothal','2'),
('0 BBY','Battle of Phindar','2'),
('0 BBY','Battle of Portocari','2'),
('0 BBY','Discovery of the Death Star','2'),
('0 BBY','Jedha insurgency','2'),
('0 BBY','Mission to the Ring of Kafrene','2'),
('0 BBY','Liberation of Erso ','2'),
('0 BBY','Operation Fracture','2'),
('0 BBY','Battle on Jedha','2'),
('0 BBY','Destruction of Jedha City','2'),
('0 BBY','Mission to Eadu ','2'),
('0 BBY','Battle of Scarif','2'),
('0 BBY','Secret mission to Tatooine','2'),
('0 BBY','The Disaster','2'),
('0 BBY','Alderaan vigil rioting','2'),
('0 BBY','Rescue of Princess Leia','2'),
('0 BBY','Battle of Yavin','2'),
('0 ABY','Ambush on Taanab','2'),
('0 ABY','Evacuation of Yavin 4','2'),
('0 ABY','Mission to rescue the survivors of Alderaan','2'),
('0 BBY','Battle of Espirion ','2'),
('0 ABY','Mission to Giju','2'),
('0 ABY','Mission to recover Imperial communication logs','2'),
('0 ABY','Skirmish in the Temple of Eedit','2'),
('0 ABY','Skirmish over Llanic','2'),
('0 ABY','Mission to Rodia','2'),
('0 ABY','Mission to Fex','2'),
('0 ABY','Mission on Denon','2'),
('0 ABY','Mission to Pasher','2'),
('0 ABY','Rescue on Omereth','2'),
('0 ABY','Attack on Cymoon 1','2'),
('0 ABY','Skirmish over an unidentified green planet','2'),
('0 ABY','Attack on an unidentified pirate base','2'),
('0 ABY','Theft of the Triple-Zero protocol personality matrix','2'),
('0 ABY','Secret mission to Geonosis','2'),
('0 ABY','Skirmish in Cylo''s research base','2'),
('0 ABY','Duel in Ben Kenobi''s home','2'),
('0 ABY','First attack on the Son-tuul Pride','2'),
('0 ABY','Son-tuul Pride robbery','2'),
('0 ABY','Escape from the Monsua Nebula','2'),
('0 ABY','Mission to the Anthan system','2'),
('0 ABY','Rescue of Luke Skywalker','2'),
('0 ABY','Mission to Shu-Torun','2'),
('0 ABY','Battle of Anthan Prime','2'),
('0 ABY','Battle of Vrogas Vas','2'),
('0 ABY','Arrth-Eno Mission','2'),
('0 ABY','Assault on Sunspot Prison','2'),
('0 ABY','War on Shu-Torun','2'),
('0 BBY','Battle at a delving citadel','2'),
('0 BBY','Attack on the ancestral retreat','2'),
('0 BBY','Battle at Rubix''s citadel ','2'),
('0 ABY','Hijacking of the Executor','2'),
('0 ABY','Skirmish on the Ghost Moon','2'),
('0 ABY','Hijacking of the Harbinger','2'),
('0 ABY','Siege on Tureen VII','2'),
('0 ABY','Escape from Skorii-Lei','2'),
('0 ABY','Mission to rescue C-3PO','2'),
('0 ABY','Mission to unidentified planet','2'),
('0 ABY','Raid at the Great Temple','2'),
('0 ABY','Twilight of the Ordu Aspectu','2'),
('0 ABY','Mission to Ktath''atn','2'),
('0 ABY','Skirmish aboard the Sorca Retreat','2'),
('0 ABY','Escape from an unidentified ocean planet','2'),
('0 ABY','Mission to Akiva','2'),
('0 ABY','Mission to Horox III','2'),
('0 ABY','Mission to Crait','2'),
('0 ABY','Arrests on Zeitooine','2'),
('1 ABY','Attack on an EF76 Nebulon-B escort frigate','2'),
('1 ABY','Bandit purges','2'),
('1 ABY','Attack on a pirate station ','2'),
('1 ABY','Skirmish aboard Accresker Jail','2'),
('1 ABY','Mid Rim Retreat','2'),
('1 ABY','Mission to Jedha','2'),
('1 ABY','Mutiny on Mon Cala','2'),
('1 ABY','Attack on the Mako-Ta Space Docks','2'),
('1 ABY','Skirmish on Hubin','2'),
('1 ABY','Attack on an Imperial Impound Yard','2'),
('1 ABY','Attack on Haidoral Prime','2'),
('2 ABY','Coyerti campaign','2'),
('1 ABY','Attack on an Imperial scout post','2'),
('1 ABY','Attack on an Imperial fort','2'),
('1 ABY','Attack on the Distillery','2'),
('1 ABY','Destruction of the Coyerti Imperial garrison ','2'),
('1 ABY','Battle in the Enrivi system','2'),
('1 ABY','Battle in the Chonsetta system','2'),
('1 ABY','Raid on an Imperial heavy freighter','2'),
('3 ABY','Infiltration of the Thunderstrike ','2'),
('3 ABY','Battle of Hoth','2'),
('3 ABY','Duel on Cloud City','2'),
('3 ABY','Escape from Cloud City','2'),
('3 ABY','Operation Ringbreaker','2'),
('3 ABY','Attack on Mardona III','2'),
('3 ABY','Attack on the dockyards of Najan-Rovi','2'),
('3 ABY','Attack on Obumubo','2'),
('3 ABY','Attack on Nakadia','2'),
('3 ABY','Battle of Naator','2'),
('3 ABY','Battle of Xagobah','2'),
('3 ABY','Attack on the Kuliquo belt asteroid mines ','2'),
('3 ABY','Siege of Inyusu Tor','2'),
('4 ABY','Operation Yellow Moon','2'),
('4 ABY','Destruction of the Shieldmaiden ','2'),
('4 ABY','Rescue of Han Solo','2'),
('4 ABY','Battle of Taanab','2'),
('4 ABY','Dogfight in the Hudalla system','2'),
('4 ABY','Bombardment of Durkteel','2'),
('4 ABY','Battle of Endor','2'),
('4 ABY','Coruscant civil war','2'),
('4 ABY','Riot in Monument Plaza ','2'),
('4 ABY','Assault on an Imperial outpost','2'),
('4 ABY','Beltire Liberation','2'),
('4 ABY','Battle of Cawa City','2'),
('4 ABY','Raid at the Wretch of Tayron','2'),
('4 ABY','Contingency','2'),
('4 ABY','Operation: Cinder','2'),
('4 ABY','Battle of Fondor','2'),
('4 ABY','Skirmish on Vardos','2'),
('4 ABY','Battle of Theed','2'),
('4 ABY','Attack on Abednedo ','2'),
('4 ABY','Iron Blockade','2'),
('4 ABY','Liberation of Bespin','2'),
('4 ABY','Attempted kidnapping of Bragh','2'),
('4 ABY','Rescue mission to the Crypt','2'),
('4 ABY','Battle of Mataou','2'),
('4 ABY','Battle of Hoth (Iron Blockade)','2'),
('4 ABY','Battle of Anoat ','2'),
('4 ABY','Battle of Malastare','2'),
('4 ABY','Battle of Naalol','2'),
('4 ABY','Operation on Geonosis','2'),
('4 ABY','Battle in Central City','2'),
('4 ABY','Battle of Sevarcos','2'),
('4 ABY','Mission to Akiva','2'),
('4 ABY','Rebellion on Akiva','2'),
('5 ABY','Mission to Vetine','2'),
('5 ABY','Skirmish on Takodana','2'),
('5 ABY','Attack on the Hyborean Moon','2'),
('5 ABY','Capture of Perwin Gedde','2'),
('5 ABY','Skirmish near Wild Space','2'),
('5 ABY','Battle of Nag Ubdur','2'),
('5 ABY','Ambush at Govneh Ridge','2'),
('5 ABY','Massacre at Binjai-Tin ','2'),
('5 ABY','Coronet City revolution','2'),
('5 ABY','Attack on a New Republic outpost','2'),
('5 ABY','Siege of Arkanis','2'),
('5 ABY','Battle for Kuat Drive Yards','2'),
('5 ABY','Liberation of Kashyyyk','2'),
('5 ABY','Imperial-Republic peace talks','2'),
('5 ABY','Attack on Chandrila ','2'),
('5 ABY','Mission to Chinook Station','2'),
('5 ABY','Destruction of an abandoned weapons depot','2'),
('5 ABY','Capture of Mercurial Swift','2'),
('5 ABY','Liberation of Nakadia','2'),
('5 ABY','Mission to Nakadia','2'),
('5 ABY','Skirmish in Freetown','2'),
('5 ABY','Naboo invasions','2'),
('5 ABY','Battle of Fondor Shipyards','2'),
('5 ABY','Assassination attempt on Mon Mothma','2'),
('5 ABY','Destruction of Imperial Star Destroyers','2'),
('5 ABY','Contingency','2'),
('5 ABY','Battle of Jakku ','2'),
('7 ABY','Karee Blockade Clutch','2'),
('7 ABY','Second skirmish in the Mesulan Remnants Belt','2'),
('7 ABY','Standoff near Substation Grimdock','2'),
('28 ABY','Amaxine warrior crisis','2'),
('28 ABY','Mission to Bastatha','2'),
('28 ABY','Napkin Bombing','2'),
('28 ABY','Mission to Sibensko','2'),
('28 ABY','Tai-Lin Garr''s assassination ','2'),
('28 ABY','Destruction of Luke Skywalker''s Jedi Temple','2'),
('31 ABY','Race for the Lost Treasure of Count Dooku','2'),
('31 ABY','Battle in the Sea of Sand','2'),
('31 ABY','Escape from the Obrexta III ','2'),
('33 ABY','Suraz engagement','2'),
('33 ABY','Skirmish in OR-Kappa-2722','2'),
('33 ABY','Mission to Taul','2'),
('33 ABY','Rescue of Admiral Ackbar','2'),
('33 ABY','Operation: Sabre Strike','2'),
('33 ABY','Hunt for Lor San Tekka','2'),
('33 ABY','Mission to Ovanis','2'),
('33 ABY','Mission to Megalox Beta ','2'),
('34 ABY','Skirmish on Pheryon','2'),
('34 ABY','Mission to Kaddak','2'),
('34 ABY','Battle over a desert planet','2'),
('34 ABY','Mission to obtain fuel','2'),
('34 ABY','Mission to Spalex','2'),
('34 ABY','Hunt for Lor San Tekka','2'),
('34 ABY','Mission to Cato Neimoidia','2'),
('34 ABY','Rescue of Lor San Tekka','2'),
('34 ABY','Mission to Pillio ','2'),
('34 ABY','Mission to rendezvous with the Resistance','2'),
('34 ABY','Mission on the Colossus platform','2'),
('34 ABY','Raid on the Colossus','2'),
('34 ABY','Mission to Doza Tower','2'),
('34 ABY','Second raid on the Colossus','2'),
('34 ABY','Second mission to Doza Tower ','2'),
('34 ABY','Massacre on Tehar','2'),
('34 ABY','Hunt for Eila and Kel','2'),
('34 ABY','Investigation of a G-class freighter','2'),
('34 ABY','Mission on the Colossus platform','2'),
('34 ABY','Second raid on the Colossus','2'),
('34 ABY','Second mission to Doza Tower ','2'),
('34 ABY','Mission to Station Theta Black','2'),
('34 ABY','Mission on the Colossus platform','2'),
('34 ABY','Theft of the phase connector','2'),
('34 ABY','Kidnapping of Torra Doza ','2'),
('34 ABY','Occupation of the Colossus','2'),
('34 ABY','Mission on the Colossus platform','2'),
('34 ABY','Escape from the Colossus ','2'),
('34 ABY','Investigation of the Dassal system','2'),
('34 ABY','Occupation of the Colossus','2'),
('34 ABY','Rescue on the Colossus','2'),
('34 ABY','Mission to contact the Resistance ','2'),
('34 ABY','Missions against pirates in the Cassander sector','2'),
('34 ABY','Battle of Mamkoda','2'),
('34 ABY','Mission to Caraxl ','2'),
('34 ABY','Strike at Pressy''s Tumble','2'),
('34 ABY','Attack on Tuanul','2'),
('34 ABY','Missions against pirates in the Cassander sector','2'),
('34 ABY','Battle of Sheh Soahi ','2'),
('34 ABY','Escape from the Finalizer','2'),
('34 ABY','Escape from Jakku','2'),
('34 ABY','Skirmish aboard the Eravana','2'),
('34 ABY','Mission to Athulla','2'),
('34 ABY','Battle of Kestro','2'),
('34 ABY','Atterra campaign','2'),
('34 ABY','Mission to Vodran ','2'),
('34 ABY','Hosnian Cataclysm','2'),
('34 ABY','Battle of Takodana','2'),
('34 ABY','Skirmish on the Retribution','2'),
('34 ABY','Battle of Starkiller Base','2'),
('34 ABY','Hunt for Rivas','2'),
('34 ABY','Mission to the Outer Rim','2'),
('34 ABY','Battle on Pastoria ','2'),
('34 ABY','Evacuation of D''Qar','2'),
('34 ABY','Mission to Canto Bight','2'),
('34 ABY','Attack on the Resistance fleet','2'),
('34 ABY','Battle of Crait','2'),
('34 ABY','Mission to the Outer Rim','2');
