use JediLibraryDB;

insert into Knights 
Values
    ('Yoda','Jedi Grand Master'),
    ('Luke Skywalker','Jedi Grand Master'),
    ('Zym','Jedi Grand Master'),
    ('Nomi Sunrider','Jedi Grand Master'),
    ('Satele Shan','Jedi Grand Master'),
    ('Saba Sebatyne','Jedi Grand Master'),
    ('Kenth Hamner','Jedi Grand Master'),
    ('Biel Ductavis','Jedi Grand Master'),
    ('Fae Coven','Jedi Grand Master'),

    ('Aqinos','Jedi Master'),
    ('Barratk''l','Jedi Master'),
    ('Cilghal','Jedi Master'),
    ('Te Corso','Jedi Master'),
    ('Winslau Da''k','Jedi Master'),
    ('Asaak Dan','Jedi Master'),
    ('Drok','Jedi Master'),
    ('Sayar Dun''La','Jedi Master'),
    ('Tedryn','Jedi Master'),
    ('Kyp Durron','Jedi Master'),
    ('Eelysa','Jedi Master'),
    ('Jaina Solo Fel','Jedi Master'),
    ('Kenth Hamner','Jedi Master'),
    ('Hira','Jedi Master'),
    ('Sirrus','Jedi Master'),
    ('Corran Horn','Jedi Master'),
    ('Ikrit','Jedi Master'),
    ('Maara Jade','Jedi Master'),
    ('K''Kruhk','Jedi Master'),
    ('Kyle Katarn','Jedi Master'),
    ('Lar Le''Ung','Jedi Master'),
    ('Tresina Lobi','Jedi Master'),
    ('Mai','Jedi Master'),
    ('Markre Medjev','Jedi Master'),
    ('Tili Qua','Jedi Master'),
    ('Octa Ramis','Jedi Master'),
    ('Ahn Rasi Tuum','Jedi Master'),
    ('Rawk','Jedi Master'),
    ('T''ra Saa','Jedi Master'),
    ('Wolf Sazen','Jedi Master'),
    ('Saba Sebatyne','Jedi Master'),
    ('Kol Skywalker','Jedi Master'),
    ('Mara Jade Skywalker','Jedi Master'),
    ('Kam Solusar','Jedi Master'),
    ('Tionne Solusar','Jedi Master'),
    ('Streen','Jedi Master'),
    ('Tobias Sun','Jedi Master'),
    ('Kirana Ti','Jedi Master'),
    ('Rasi Tuum','Jedi Master'),
    ('Shado Vao','Jedi Master'),
    ('X2','Jedi Master'),
    ('Mander Zuma','Jedi Master'),
('Chon Actrion','Jedi Master'),
('Adelade','Jedi Master'),
('Sar Agorn','Jedi Master'),
('Unaw Aharo','Jedi Master'),
('Alaqua','Jedi Master'),
('Seraph Alde','Jedi Master'),
('Alekam','Jedi Master'),
('Dakshee Alabar','Jedi Master'),
('Ali-Alann','Jedi Master'),
('Ali-Vor','Jedi Master'),
('Stass Allie','Jedi Master'),
('Jesper Altax','Jedi Master'),
('Djinn Altis','Jedi Master'),
('Ring-Sol Ambase','Jedi Master'),
('Talena Ancia','Jedi Master'),
('Andria','Jedi Master'),
('Gar Anstak','Jedi Master'),
('Jon Antilles','Jedi Master'),
('Aqinos','Jedi Master'),
('Koffi Arana','Jedi Master'),
('Ardray','Jedi Master'),
('Arias','Jedi Master'),
('Arjur','Jedi Master'),
('Darrin Arkanian','Jedi Master'),
('Aryzah','Jedi Master'),
('Ausar Auset','Jedi Master'),
('Averon','Jedi Master'),
('Kosul Ayada','Jedi Master'),
('Bodo Baas','Jedi Master'),
('Vodo-Siosk Baas','Jedi Master'),
('Bacara','Jedi Master'),
('Haaran Balmor','Jedi Master'),
('Ban-yaro','Jedi Master'),
('Po Bandis','Jedi Master'),
('Barra-Rona-Ban','Jedi Master'),
('Daakman Barrek','Jedi Master'),
('The Barsen''thor The Third','Jedi Master'),
('Bastra','Jedi Master'),
('Soon Bayts','Jedi Master'),
('Bear (Jedi)','Jedi Master'),
('Bedoch','Jedi Master'),
('Benn','Jedi Master'),
('Berethon','Jedi Master'),
('Berluk','Jedi Master'),
('Depa Billaba','Jedi Master'),
('Ood Bnar','Jedi Master'),
('Ashka Boda','Jedi Master'),
('Bolook','Jedi Master'),
('Anoon Bondara','Jedi Master'),
('Z''meer Bothu','Jedi Master'),
('Boudyn','Jedi Master'),
('Bowspritz','Jedi Master'),
('Waldan Bridger','Jedi Master'),
('Brohmer','Jedi Master'),
('Kei Loo Bross','Jedi Master'),
('Jorus C''baoth','Jedi Master'),
('Cabaril','Jedi Master'),
('Nareen Cale','Jedi Master'),
('Iri Camas','Jedi Master'),
('Caudle','Jedi Master'),
('Cerik','Jedi Master'),
('Ceryss','Jedi Master'),
('Morrit Ch''gally','Jedi Master'),
('Chamma','Jedi Master'),
('Bol Chatak','Jedi Master'),
('Vokara Che','Jedi Master'),
('Toluz Cheq','Jedi Master'),
('Rou Cheryen','Jedi Master'),
('Tsui Choi','Jedi Master'),
('Chonu','Jedi Master'),
('Chuang','Jedi Master'),
('Crozwon','Jedi Master'),
('Dajjun','Jedi Master'),
('Taria Damsin','Jedi Master'),
('Athleenia Dannuz','Jedi Master'),
('Poli Dapatian','Jedi Master'),
('Dar''Nala','Jedi Master'),
('Chu-Gon Dar','Jedi Master'),
('Kao Cen Darach','Jedi Master'),
('Noa-Jek Darillian','Jedi Master'),
('Roblio Darté','Jedi Master'),
('Daxarn','Jedi Master'),
('Rekpa De','Jedi Master'),
('Ivixa Delbaeth','Jedi Master'),
('Delsa','Jedi Master'),
('Denia','Jedi Master'),
('Liam Dentiri','Jedi Master'),
('Darth Desolous','Jedi Master'),
('Winna Di Yuni','Jedi Master'),
('Ima-Gun Di','Jedi Master'),
('Nico Diath','Jedi Master'),
('Sidrona Diath','Jedi Master'),
('Sakan Do''nair','Jedi Master'),
('Dobe','Jedi Master'),
('Reesa Doliq','Jedi Master'),
('Dolso','Jedi Master'),
('Dominus','Jedi Master'),
('Dooku','Jedi Master'),
('T''chooka D''oon','Jedi Master'),
('Dorak','Jedi Master'),
('Tantron Dow','Jedi Master'),
('Worror Dowmat','Jedi Master'),
('Krynda Draay','Jedi Master'),
('Cin Drallig','Jedi Master'),
('Tho-Mes Drei','Jedi Master'),
('Relin Druur','Jedi Master'),
('Ur-Sema Du','Jedi Master'),
('Biel Ductavis','Jedi Master'),
('Jaled Dur','Jedi Master'),
('Duumas','Jedi Master'),
('Dynaroth','Jedi Master'),
('Allynic E''Kles','Jedi Master'),
('Aurei Eadon','Jedi Master'),
('Ebebdian','Jedi Master'),
('Sta-Den Eekin','Jedi Master'),
('Bant Eerin','Jedi Master'),
('Ezar Elasra','Jedi Master'),
('Elmel','Jedi Master'),
('Eskel','Jedi Master'),
('Everen Ettene','Jedi Master'),
('Evrios','Jedi Master'),
('Vo''ren Faalo','Jedi Master'),
('Duras Fain','Jedi Master'),
('Valenthyne Farfalla','Jedi Master'),
('Farlonn','Jedi Master'),
('Jastus Farr','Jedi Master'),
('Fay','Jedi Master'),
('Jonas Fel''Kona','Jedi Master'),
('Minos Fel''Kona','Jedi Master'),
('Fellil','Jedi Master'),
('Feln','Jedi Master'),
('Ferroda','Jedi Master'),
('Fin-So-Rowan','Jedi Master'),
('Kit Fisto','Jedi Master'),
('Devan For''deschel','Jedi Master'),
('Newar Forrth','Jedi Master'),
('Four Masters','Jedi Master'),
('Berin Fraal','Jedi Master'),
('Frann','Jedi Master'),
('Kast Fulier','Jedi Master'),
('Futrad','Jedi Master'),
('Fy-Tor-Ana','Jedi Master'),
('Vaas Ga','Jedi Master'),
('Adi Gallia','Jedi Master'),
('Galong-Tal','Jedi Master'),
('Garault','Jedi Master'),
('Sidonie Garen','Jedi Master'),
('Garfield','Jedi Master'),
('Garnoo','Jedi Master'),
('Garragor','Jedi Master'),
('Kalisa Gehnso','Jedi Master'),
('Gelleric','Jedi Master'),
('Genarra','Jedi Master'),
('Cedral Gend','Jedi Master'),
('Gerata','Jedi Master'),
('Ges-Su-Kai','Jedi Master'),
('Glaive','Jedi Master'),
('Glynn-Beti','Jedi Master'),
('Wom-Nii Gnaden','Jedi Master'),
('Gnost-Dural','Jedi Master'),
('N''Kata Del Gormo','Jedi Master'),
('Gra''aton','Jedi Master'),
('Arlo Grennen','Jedi Master'),
('Seigford Grey','Jedi Master'),
('Grohto','Jedi Master'),
('Groj','Jedi Master'),
('Jook-jook H''broozin','Jedi Master'),
('Kina Ha','Jedi Master'),
('Halacia','Jedi Master'),
('Nejaa Halcyon','Jedi Master'),
('Hallis','Jedi Master'),
('Halsey','Jedi Master'),
('Halykus','Jedi Master'),
('Handa','Jedi Master'),
('Hasslo','Jedi Master'),
('Helarin','Jedi Master'),
('Heljus','Jedi Master'),
('Hero of Tython','Jedi Master'),
('Rorkys Hesh','Jedi Master'),
('Toma Hi''llani','Jedi Master'),
('Tolan Hing','Jedi Master'),
('Wren Honoran','Jedi Master'), 
('Hortath','Jedi Master'), 
('Kai Hudorra','Jedi Master'), 
('Jerbhen Hulis','Jedi Master'), 
('Noab Hulis','Jedi Master'), 
('Cassa Hun','Jedi Master'), 
('Tyus Huols','Jedi Master'), 
('Hylon','Jedi Master'), 
('Rhana Hyss','Jedi Master'), 
('Binn Ibes','Jedi Master'), 
('Belsed-Qan Idan','Jedi Master'), 
('Ikrit','Jedi Master'), 
('Illares','Jedi Master'), 
('Kirak Infil''a','Jedi Master'), 
('Injaye','Jedi Master'), 
('Jabidus Inspra','Jedi Master'), 
('Berr Irichmin','Jedi Master'), 
('JanMicénte','Jedi Master'), 
('Kellian Jarro','Jedi Master'), 
('Mroon Jassa','Jedi Master'), 
('Darrus Jeht','Jedi Master'), 
('Sian Jeisel','Jedi Master'), 
('Dass Jennir','Jedi Master'), 
('Tarben Jenoquan','Jedi Master'), 
('Jerec (Inquisitor)','Jedi Master'), 
('Anora Jessel','Jedi Master'), 
('Arca Jeth','Jedi Master'), 
('Qui-Gon Jinn','Jedi Master'), 
('Jmmaar','Jedi Master'), 
('Joce','Jedi Master'), 
('Jojighar','Jedi Master'), 
('Jormin','Jedi Master'), 
('Jorol','Jedi Master'), 
('Jrul','Jedi Master'), 
('Judd','Jedi Master'), 
('Mierme Unill','Jedi Master'), 
('The Unknown Master','Jedi Master'), 
('Unskette','Jedi Master'), 
('Upulu','Jedi Master'), 
('Ssusk Uru','Jedi Master'), 
('Usma','Jedi Master'), 
('B''ink Utrila','Jedi Master'), 
('Uvell','Jedi Master'), 
('Va''too','Jedi Master'), 
('Wole Vahn','Jedi Master'), 
('Valara','Jedi Master'), 
('Vallis','Jedi Master'), 
('Vamilad','Jedi Master'), 
('Vant','Jedi Master'), 
('Vanukar','Jedi Master'), 
('Reena Vari','Jedi Master'), 
('Skarch Vaunk','Jedi Master'), 
('Kez Velaz','Jedi Master'), 
('Knol Ven''nari','Jedi Master'), 
('Eraski Ven','Jedi Master'), 
('Sarissa Ven','Jedi Master'), 
('Broden Kel Verdox','Jedi Master'), 
('Silmis Vey','Jedi Master'), 
('Vikto','Jedi Master'), 
('Astaal Vilbum','Jedi Master'), 
('Synred Vols','Jedi Master'), 
('Vonkhel','Jedi Master'), 
('Cei Vookto','Jedi Master'), 
('Quinlan Vos','Jedi Master'), 
('Eriz Vossan','Jedi Master'), 
('Vulatan','Jedi Master'), 
('Bor-Kal Vuluk','Jedi Master'), 
('Cyman Walz','Jedi Master'), 
('Anno Wen-Chii','Jedi Master'), 
('Utnesi Wesk','Jedi Master'), 
('Wettle','Jedi Master'), 
('Mace Windu','Jedi Master'), 
('Wiwa','Jedi Master'), 
('Meeb Wix','Jedi Master'), 
('Phin-Law Wo','Jedi Master'), 
('Tharence Wo','Jedi Master'), 
('Wyellett','Jedi Master'), 
('Wytho','Jedi Master'), 
('Xamar','Jedi Master'), 
('Ilena Xan','Jedi Master'), 
('Xandyk','Jedi Master'), 
('Yaddle','Jedi Master'), 
('Ubed Yalla','Jedi Master'), 
('Yan-De','Jedi Master'), 
('Yerem','Jedi Master'), 
('Yollo','Jedi Master'), 
('Yonlach','Jedi Master'), 
('Yul-Li','Jedi Master'), 
('Ven Zallow','Jedi Master'), 
('Mavra Zane','Jedi Master'), 
('Zao','Jedi Master'), 
('Mical','Jedi Master'), 
('Zarius','Jedi Master'), 
('Kalatosh Zavros','Jedi Master'), 
('Arligan Zey','Jedi Master'), 
('Zhin','Jedi Master'), 
('Ngani Zho','Jedi Master'), 
('Va Zhurro','Jedi Master'), 
('Nerra Ziveri','Jedi Master'), 
('Zua','Jedi Master'), 
('Zunor','Jedi Master'), 
('Zylvarstar','Jedi Master'), 
('Bruu Jun-Fan','Jedi Master'), 
('Jurahi','Jedi Master'), 
('Jurokk','Jedi Master'), 
('K''Kruhk','Jedi Master'), 
('K''ungfu','Jedi Master'), 
('Tobar Ka-Teen','Jedi Master'), 
('Skere Kaan','Jedi Master'), 
('Arren Kae','Jedi Master'), 
('Kagoro','Jedi Master'), 
('Kaim','Jedi Master'), 
('Rajivari','Jedi Master'), 
('Kal-Don','Jedi Master'), 
('Kaldona','Jedi Master'), 
('Kam','Jedi Master'),
('Needa Kame','Jedi Master'), 
('Kanda','Jedi Master'), 
('Baird Kantoo','Jedi Master'), 
('Volfe Karkko','Jedi Master'), 
('Nomen Karr','Jedi Master'), 
('Karu','Jedi Master'),
('Ludwin Katarkus','Jedi Master'), 
('Coleman Kcaj','Jedi Master'), 
('Orbis Keln','Jedi Master'), 
('Harro Kelpura','Jedi Master'), 
('Kelthan','Jedi Master'), 
('Obi-Wan Kenobi','Jedi Master'), 
('Kep-She','Jedi Master'), 
('Khoris','Jedi Master'), 
('Khoveri','Jedi Master'), 
('Ki-Adi-Mundi','Jedi Master'), 
('Plun Kil','Jedi Master'), 
('Chankar Kim','Jedi Master'), 
('Ronhar Kim','Jedi Master'), 
('Kirbi','Jedi Master'), 
('Kirlocca','Jedi Master'), 
('Klydeker','Jedi Master'), 
('Agen Kolar','Jedi Master'), 
('Shon Kon Ray','Jedi Master'), 
('Uro Koo','Jedi Master'), 
('Plo Koon','Jedi Master'), 
('Jayshon Korden','Jedi Master'), 
('Kossex','Jedi Master'), 
('Rahm Kota','Jedi Master'), 
('Eeth Koth','Jedi Master'), 
('Matarmeno Krahnn','Jedi Master'), 
('Kras''dohk','Jedi Master'), 
('Darth Krayt','Jedi Master'), 
('Pong Krell','Jedi Master'), 
('Alxa Kress','Jedi Master'), 
('Asli Krimsan','Jedi Master'), 
('Erg Krow','Jedi Master'), 
('Kun','Jedi Master'), 
('An''ya Kuro','Jedi Master'), 
('Polvin Kut','Jedi Master'), 
('Dav Kylanu','Jedi Master'), 
('Lackbar','Jedi Master'), 
('Lamar the Fifth','Jedi Master'), 
('Landai','Jedi Master'), 
('Lankost','Jedi Master'), 
('Last Curator of Records','Jedi Master'), 
('Nan Latourain','Jedi Master'), 
('Maks Leem','Jedi Master'), 
('Thracia Cho Leem','Jedi Master'), 
('Leska','Jedi Master'), 
('Zhar Lestin','Jedi Master'), 
('Liv''trai','Jedi Master'), 
('Lo-Jad','Jedi Master'), 
('Lodaka','Jedi Master'), 
('Saras Loorne','Jedi Master'), 
('Loposa','Jedi Master'), 
('Lorenn','Jedi Master'), 
('Lorik','Jedi Master'), 
('Raskta Lsu','Jedi Master'), 
('Lunis','Jedi Master'), 
('Luquena','Jedi Master'), 
('Lyoon','Jedi Master'), 
('Lyron','Jedi Master'), 
('Nuck Lyu','Jedi Master'), 
('Willm Lywin','Jedi Master'), 
('M''Ba-Tee','Jedi Master'), 
('Tra''s M''ins','Jedi Master'), 
('Justyn Ma''Ning','Jedi Master'), 
('Ma''tien','Jedi Master'), 
('Hyris-Well Madorin','Jedi Master'), 
('Du Mahn','Jedi Master'), 
('Siolo Ur Manka','Jedi Master'), 
('Cherff Maota','Jedi Master'), 
('Mara (M4-78)','Jedi Master'), 
('Vij Markos','Jedi Master'), 
('Marspa','Jedi Master'), 
('Jai Maruk','Jedi Master'), 
('Miduis','Jedi Master'), 
('Mas Missur','Jedi Master'), 
('Sora Mobari','Jedi Master'), 
('Voolvif Monn','Jedi Master'), 
('Moran','Jedi Master'), 
('Oorrl Morm','Jedi Master'), 
('Celeste Morne','Jedi Master'), 
('Mickey Mouse','Jedi Master'), 
('Muheeda','Jedi Master'), 
('Garen Muln','Jedi Master'), 
('Murrtaggh','Jedi Master'), 
('Cyslin Myr','Jedi Master'), 
('Memit Nadill','Jedi Master'), 
('Nagarreken','Jedi Master'), 
('Nat-Sem','Jedi Master'), 
('Neebo','Jedi Master'), 
('Nemo','Jedi Master'), 
('Ni-Cada','Jedi Master'), 
('Nimi','Jedi Master'), 
('Bala Nisi','Jedi Master'), 
('Norcuna','Jedi Master'), 
('Qornah','Jedi Master'), 
('Notka','Jedi Master'),
('Jocasta Nu','Jedi Master'), 
('Ares Nune','Jedi Master'), 
('Nystammall','Jedi Master'), 
('Kutri O''a','Jedi Master'), 
('Obai','Jedi Master'), 
('Obba','Jedi Master'), 
('Obip','Jedi Master'), 
('Qalsneek','Jedi Master'), 
('Ocera','Jedi Master'),
('Odan-Urr','Jedi Master'), 
('Ogan-Dei','Jedi Master'), 
('Oh''dvek','Jedi Master'), 
('Onok','Jedi Master'), 
('Ooroo','Jedi Master'), 
('Kanzhei Opli','Jedi Master'), 
('Nomar Organa','Jedi Master'), 
('Tharis Orne','Jedi Master'), 
('Ilia Orpin','Jedi Master'), 
('Ortraag','Jedi Master'), 
('Oshi-Jid','Jedi Master'), 
('Ostar-Gal','Jedi Master'), 
('Barel Ovair','Jedi Master'), 
('Ajunta Pall','Jedi Master'), 
('Yuon Par','Jedi Master'), 
('Kazdan Paratus','Jedi Master'), 
('Paria','Jedi Master'), 
('Peerce','Jedi Master'), 
('Pernicar','Jedi Master'), 
('Ph''ton','Jedi Master'), 
('Phrayan','Jedi Master'), 
('Even Piell','Jedi Master'), 
('Awdrysta Pina','Jedi Master'), 
('Plautopseum','Jedi Master'), 
('Plett','Jedi Master'), 
('Yarael Poof','Jedi Master'), 
('Avan Post','Jedi Master'), 
('Shadday Potkin','Jedi Master'),  
('Pradoc','Jedi Master'), 
('Prokreisha','Jedi Master'), 

('A.J.','Jedi Knight'), 
('Tresten Agai''i','Jedi Knight'), 
('Akial','Jedi Knight'), 
('Alicka','Jedi Knight'), 
('Allya','Jedi Knight'), 
('Rees Alrix','Jedi Knight'), 
('Serifa Altunen','Jedi Knight'), 
('Alurali','Jedi Knight'), 
('Tren Alvar','Jedi Knight'), 
('Ambaln','Jedi Knight'), 
('Xiaan Amersu','Jedi Knight'), 
('Vel Ardox','Jedi Knight'), 
('Tafasheel Arkan','Jedi Knight'), 
('Evan Asani','Jedi Knight'), 
('Fable Astin','Jedi Knight'), 
('Felanil Baaks','Jedi Knight'), 
('Ara Barotta','Jedi Knight'), 
('Nem Bees','Jedi Knight'), 
('Beldorion','Jedi Knight'), 
('Mol Beldun','Jedi Knight'), 
('Nysis Belzara','Jedi Knight'), 
('Cho''na Bene','Jedi Knight'), 
('Bob (Jedi)','Jedi Knight'), 
('Aidan Bok','Jedi Knight'), 
('Niebur Boton','Jedi Knight'), 
('Empatojayos Brand','Jedi Knight'), 
('Winso Bykart','Jedi Knight'), 
('Rallcema Bylissura','Jedi Knight'), 
('Cal-i-Vaun','Jedi Knight'), 
('Dalnus Cam','Jedi Knight'), 
('Dee-Lynn Cance','Jedi Knight'), 
('Alysun Celz','Jedi Knight'), 
('Olana Chion','Jedi Knight'), 
('Chellemi Chuovvick','Jedi Knight'), 
('Nygreena Clo','Jedi Knight'), 
('Constanten','Jedi Knight'), 
('Amar Cros','Jedi Knight'), 
('Krin D''bis','Jedi Knight'), 
('Vima-Da-Boda','Jedi Knight'), 
('Hart Daele','Jedi Knight'), 
('Weren Dal','Jedi Knight'), 
('Joclad Danva','Jedi Knight'), 
('Miro Daroon','Jedi Knight'), 
('Ameesa Darys','Jedi Knight'), 
('Jarid DeBell','Jedi Knight'), 
('Lexi Degarienne','Jedi Knight'), 
('Desertwind','Jedi Knight'), 
('Kir-Tja Dilsn','Jedi Knight'), 
('Vydel Dir''Nul','Jedi Knight'), 
('Kin-Ya Dosun','Jedi Knight'), 
('Anakin Skywalker','Jedi Knight'), 
('Valin Draco','Jedi Knight'), 
('Jor Drakas','Jedi Knight'), 
('Fenella Druce','Jedi Knight'), 
('Jiv Durael','Jedi Knight'), 
('Durnar','Jedi Knight'), 
('Dustrose','Jedi Knight'), 
('Rii''ke En','Jedi Knight'), 
('Neth Enasteri','Jedi Knight'), 
('Eon','Jedi Knight'), 
('Geith Eris','Jedi Knight'), 
('Bleth Fahr','Jedi Knight'), 
('Feemor','Jedi Knight'), 
('Force Vampire','Jedi Knight'), 
('Siadem Forte','Jedi Knight'), 
('Gel','Jedi Knight'), 
('Plessus Ghon','Jedi Knight'), 
('Gira','Jedi Knight'), 
('Falon Grey','Jedi Knight'), 
('Halbret','Jedi Knight'), 
('Keiran Halcyon','Jedi Knight'), 
('Sharad Hett','Jedi Knight'), 
('Bashinan Hodizwen','Jedi Knight'), 
('Dovish Hokken','Jedi Knight'), 
('Anise I''Zak','Jedi Knight'), 
('Tnani Ikon','Jedi Knight'), 
('Sana-Jis Ilowa','Jedi Knight'), 
('Ylenic It''kla','Jedi Knight'), 
('J''Mikel','Jedi Knight'), 
('Renij Jaa','Jedi Knight'), 
('Nanda-Ree Janoo','Jedi Knight'), 
('Jedi Jewels','Jedi Knight'), 
('Sarrissa Jeng','Jedi Knight'), 
('Lorana Jinzler','Jedi Knight'), 
('Klis Joo','Jedi Knight'), 
('Tassida Judrelle','Jedi Knight'), 
('Taj Junak','Jedi Knight'), 
('Bardan Jusik','Jedi Knight'), 
('Kai Justiss','Jedi Knight'), 
('Jwartek','Jedi Knight'), 
('K''kur','Jedi Knight'), 
('Kadann','Jedi Knight'), 
('Reess Kairn','Jedi Knight'), 
('Clarin Karagan','Jedi Knight'), 
('Aruden Kej','Jedi Knight'), 
('Selig Kenjenn','Jedi Knight'), 
('Danaan Kerr','Jedi Knight'), 
('Serra Keto','Jedi Knight'), 
('Squire Kinning','Jedi Knight'), 
('Seenlu Kir','Jedi Knight'), 
('Sha Koon','Jedi Knight'), 
('Jodoo Kreen','Jedi Knight'), 
('Iwo Kulka','Jedi Knight'), 
('Kydra','Jedi Knight'), 
('Nek Lawsirk','Jedi Knight'), 
('Jang Li-Li','Jedi Knight'), 
('Lissarkh','Jedi Knight'), 
('Lobis Lobin','Jedi Knight'), 
('Lycan','Jedi Knight'), 
('Ma''ya','Jedi Knight'), 
('Zeetara Maan','Jedi Knight'), 
('Oden Malksch','Jedi Knight'), 
('Easal Mar','Jedi Knight'), 
('Kento Marek','Jedi Knight'), 
('Roth-Del Masona','Jedi Knight'), 
('Meloria','Jedi Knight'), 
('Ichi-Tan Micoda','Jedi Knight'), 
('Minch','Jedi Knight'), 
('Callista Ming','Jedi Knight'), 
('Dazen Mok','Jedi Knight'), 
('Kaddo Moll','Jedi Knight'), 
('Talia Moonseeker','Jedi Knight'), 
('Foul Moudama','Jedi Knight'), 
('Mynnic','Jedi Knight'), 
('Naeshahn','Jedi Knight'), 
('Karae Nalvas','Jedi Knight'), 
('Florg Nerfherder','Jedi Knight'), 
('Tieren Nie-Tan','Jedi Knight'), 
('Niquon','Jedi Knight'), 
('Noga-ta','Jedi Knight'), 
('Lari Oll','Jedi Knight'), 
('Bar Oplut','Jedi Knight'), 
('Johun Othone','Jedi Knight'), 
('Pann','Jedi Knight'), 
('Jax Pavan','Jedi Knight'), 
('Pendo','Jedi Knight'), 
('Torhaa Phaa','Jedi Knight'), 
('Pinky','Jedi Knight'), 
('Olge Plavi-Dol','Jedi Knight'), 
('Politrix','Jedi Knight'), 
('Qid Proko','Jedi Knight'), 
('Loo Raelo','Jedi Knight'), 
('Rana','Jedi Knight'), 
('Yoshi Raph-Elan','Jedi Knight'), 
('Reeft','Jedi Knight'), 
('Kai Rees','Jedi Knight'), 
('Tyneir Renz','Jedi Knight'), 
('Khen Reo','Jedi Knight'), 
('Keelyvine Reus','Jedi Knight'), 
('Et Rex','Jedi Knight'), 
('Trevon Rey','Jedi Knight'), 
('Rivi-Anu','Jedi Knight'), 
('Aven Rolk','Jedi Knight'), 
('Rorr''hn','Jedi Knight'), 
('Ixian Rovieda','Jedi Knight'), 
('Jude Rozess','Jedi Knight'), 
('Rulo','Jedi Knight'), 
('Seek Ryontarr','Jedi Knight'), 
('L''lacielo Sageon','Jedi Knight'), 
('Ji-Ad Sarain','Jedi Knight'), 
('Sardoth','Jedi Knight'), 
('Seeth''tal','Jedi Knight'), 
('Tarr Seirr','Jedi Knight'), 
('Naia Sendar','Jedi Knight'), 
('Kadrian Sey','Jedi Knight'), 
('Kasi Sha''Rhil','Jedi Knight'), 
('Dar Singe','Jedi Knight'), 
('Vinian Ska','Jedi Knight'), 
('Tol Skorr','Jedi Knight'), 
('Yrada Soludisan','Jedi Knight'), 
('Milak Sonloam','Jedi Knight'), 
('Soonis','Jedi Knight'), 
('Morvet Storm','Jedi Knight'), 
('Zelice Sturm','Jedi Knight'), 
('Jaizen Suel','Jedi Knight'), 
('Sukarr','Jedi Knight'), 
('Fe Sun','Jedi Knight'), 
('Frey Suun','Jedi Knight'), 
('Alam Syk','Jedi Knight'), 
('T''Bolton','Jedi Knight'), 
('T''Seely','Jedi Knight'), 
('Syr Tal-Soten','Jedi Knight'), 
('Ofar Tan-Doov','Jedi Knight'), 
('Medd Tandar','Jedi Knight'), 
('Michael Tandre','Jedi Knight'), 
('Damien Tantrellius','Jedi Knight'), 
('Laranth Tarak','Jedi Knight'), 
('Rhad Tarn','Jedi Knight'), 
('Taselda','Jedi Knight'), 
('Dorn Tavers','Jedi Knight'), 
('Jafer Torles','Jedi Knight'), 
('Flint Torul','Jedi Knight'), 
('Traavis','Jedi Knight'), 
('Travgen','Jedi Knight'), 
('Axton Tredway','Jedi Knight'), 
('Treibeiu','Jedi Knight'), 
('Tu''ala','Jedi Knight'), 
('Ish-Bel Tur','Jedi Knight'), 
('Etain Tur-Mukan','Jedi Knight'), 
('Lilit Twoseas','Jedi Knight'), 
('Nikkos Tyris','Jedi Knight'), 
('Ainvar ul-Esca','Jedi Knight'), 
('Valiri','Jedi Knight'), 
('Sarn Vals','Jedi Knight'), 
('Tru Veld','Jedi Knight'), 
('Halagad Ventor','Jedi Knight'), 
('Vergere','Jedi Knight'), 
('Mana Veridi','Jedi Knight'), 
('Bodis-Ker Vitan','Jedi Knight'), 
('Tensa Voll','Jedi Knight'), 
('Vorlocca','Jedi Knight'), 
('Suljo Warde','Jedi Knight'), 
('Talilia Weden','Jedi Knight'), 
('Sia-Lan Wezz','Jedi Knight'), 
('Winnoa','Jedi Knight'), 
('Sarro Xaj','Jedi Knight'), 
('Xeltek','Jedi Knight'), 
('Kindee Ya','Jedi Knight'), 
('Borik Yelgo','Jedi Knight'), 
('Noro Zak','Jedi Knight'), 
('Cho Zeh''Bra','Jedi Knight'), 
('Ana Zett','Jedi Knight'), 
('Zuth','Jedi Knight'), 
('Algrunar','Jedi Knight'), 
('Anyara','Jedi Knight'), 
('Aru-Wen','Jedi Knight'), 
('Ayesho','Jedi Knight'), 
('Belaya','Jedi Knight'), 
('Cale Berkona','Jedi Knight'), 
('Jilst Bindalin','Jedi Knight'), 
('Blendri','Jedi Knight'), 
('Briqui','Jedi Knight'), 
('Samuro','Jedi Knight'), 
('Bynin','Jedi Knight'), 
('Zayne Carrick','Jedi Knight'), 
('Kira Carsen','Jedi Knight'), 
('Ceras','Jedi Knight'), 
('Kiel Charny','Jedi Knight'), 
('Jomar Chul','Jedi Knight'), 
('Shoaneb Culu','Jedi Knight'), 
('Duqua Dar','Jedi Knight'), 
('Shannur Darkstar','Jedi Knight'), 
('Aldren Dayos','Jedi Knight'), 
('Deelguh','Jedi Knight'), 
('Karist Dem','Jedi Knight'), 
('Dace Diath','Jedi Knight'), 
('Iann Doaba','Jedi Knight'), 
('Ako Domi','Jedi Knight'), 
('Tott Doneeta','Jedi Knight'), 
('Barrison Draay','Jedi Knight'), 
('Draerd','Jedi Knight'), 
('Exteen','Jedi Knight'), 
('Ezeraline','Jedi Knight'), 
('Laranna Fain','Jedi Knight'), 
('Ferroh','Jedi Knight'), 
('Attros Finn','Jedi Knight'), 
('Gale','Jedi Knight'), 
('Fortris Gall','Jedi Knight'), 
('Veag Gonwa','Jedi Knight'), 
('Dvakvar Grahrk','Jedi Knight'), 
('Halbret','Jedi Knight'), 
('Drevveka Hoctu','Jedi Knight'), 
('Kerra Holt','Jedi Knight'), 
('Tau Idair','Jedi Knight'), 
('Iunist','Jedi Knight'), 
('Deesra Luur Jada','Jedi Knight'), 
('Danah Jor','Jedi Knight'), 
('Juhani','Jedi Knight'), 
('Kith Kark','Jedi Knight'), 
('Ardun Kothe','Jedi Knight'), 
('Kursil','Jedi Knight'), 
('Laotah','Jedi Knight'), 
('Aryn Leneer','Jedi Knight'), 
('Lirondo','Jedi Knight'), 
('Zona Luka','Jedi Knight'), 
('Ma''ya','Jedi Knight'), 
('Darth Malak','Jedi Knight'), 
('Adeline Marr','Jedi Knight'), 
('Jelph Marrian','Jedi Knight'), 
('Crian Maru','Jedi Knight'), 
('Mashallon','Jedi Knight'), 
('Darb Misken','Jedi Knight'), 
('Leeha Narezz','Jedi Knight'), 
('Vara Nreem','Jedi Knight'), 
('Shaela Nuur','Jedi Knight'), 
('Nae Nuuv','Jedi Knight'), 
('Ralon Nys','Jedi Knight'), 
('Okean','Jedi Knight'), 
('Yem Ordalien','Jedi Knight'), 
('Jari Orez','Jedi Knight'), 
('Orus','Jedi Knight'), 
('Johun Othone','Jedi Knight'), 
('Nadai Pawaro','Jedi Knight'), 
('Pendo','Jedi Knight'), 
('Petja','Jedi Knight'), 
('Derrica Praji','Jedi Knight'), 
('Nariel Pridence','Jedi Knight'), 
('Cay Qel-Droma','Jedi Knight'), 
('Duron Qel-Droma','Jedi Knight'), 
('Ulic Qel-Droma','Jedi Knight'), 
('Choza Raabat','Jedi Knight'), 
('Keval Raffaan','Jedi Knight'), 
('Rajan','Jedi Knight'), 
('Vici Ramunee','Jedi Knight'), 
('Guun Han Saresh','Jedi Knight'), 
('Warren Sedoru','Jedi Knight'), 
('Sedoya Senn','Jedi Knight'), 
('Goril Sevintran','Jedi Knight'), 
('Shalavaa','Jedi Knight'), 
('Tasiele Shan','Jedi Knight'), 
('Vollen Sor','Jedi Knight'), 
('Anavus Svag','Jedi Knight'), 
('Sylvar','Jedi Knight'), 
('Taradon','Jedi Knight'), 
('Taren Vor','Jedi Knight'), 
('Technobeast Jedi','Jedi Knight'), 
('Tephan','Jedi Knight'), 
('Tyler Thello','Jedi Knight'), 
('Qrrrl Toq','Jedi Knight'), 
('Salen Toth','Jedi Knight'), 
('Rojo Trace','Jedi Knight'), 
('Ulldin','Jedi Knight'), 
('Woir Ur''naght','Jedi Knight'), 
('Keiran Valn','Jedi Knight'), 
('Bavik Vannor','Jedi Knight'), 
('Volryder','Jedi Knight'), 
('Roni von Wasaki','Jedi Knight'), 
('Derrin Weller','Jedi Knight'), 
('Sallius Wen','Jedi Knight'), 
('Oss Wilum','Jedi Knight'), 
('Winnoa','Jedi Knight'), 
('Sarro Xaj','Jedi Knight'), 
('Xendor','Jedi Knight'), 
('Xerender','Jedi Knight'), 
('Rolend Zavros','Jedi Knight'), 
('Yanila Zavros','Jedi Knight'), 
('Bataui Zeel','Jedi Knight'), 
('Do Zonn','Jedi Knight'), 
('Zylixx','Jedi Knight'), 
('Nordia Gral','Je''daii Temple Master'), 
('Fable Astin','Jedi Padawan'),
('Ezra Bridger','Jedi Padawan'),
('Drun Cairnwick','Jedi Padawan'),
('Gruu Dunrik','Jedi Padawan'),
('Ylenic It''kla','Jedi Padawan'),
('Kanan Jarrus','Jedi Padawan'),
('Jedi Prisoner','Jedi Padawan'),
('Drakka Judarrl','Jedi Padawan'),
('Ephaan Kenzon','Jedi Padawan'),
('Rahm Kota','Jedi Padawan'),
('Galen Marek','Jedi Padawan'),
('Mickey Mouse','Jedi Padawan'),
('Ferus Olin','Jedi Padawan'),
('Qu Rahn','Jedi Padawan'),
('Tyneir Renz','Jedi Padawan'),
('Rorr''hn','Jedi Padawan'),
('Corwin Shelvay','Jedi Padawan'),
('Echuu Shen-Jon','Jedi Padawan'),
('Rachi Sitra','Jedi Padawan'),
('Starkiller','Jedi Padawan'),
('Dorn Tavers','Jedi Padawan');